# Generated by Django 4.0.4 on 2022-04-21 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=12)),
                ('size', models.BigIntegerField()),
                ('is_file', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('root_directory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.file')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('root_directory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.file')),
            ],
        ),
    ]
