# Generated by Django 4.0.4 on 2022-05-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_profile_alter_file_parent_id_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.file'),
        ),
    ]
