# Generated by Django 4.0.4 on 2022-05-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_file_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='parent_id',
            new_name='parent_directory',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='root_directory_id',
            new_name='root_directory',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='root_directory_id',
            new_name='root_directory',
        ),
    ]
