# Generated by Django 4.0.4 on 2022-06-22 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_parent_id_file_parent_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_file',
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(max_length=64),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=64)),
                ('contents_size', models.BigIntegerField()),
                ('parent_directory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.directory')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.directory'),
        ),
        migrations.AlterField(
            model_name='group',
            name='root_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.directory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='root_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.directory'),
        ),
    ]
