# Generated by Django 4.0.4 on 2022-06-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_file_is_file_alter_file_name_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.directory'),
        ),
    ]
