# Generated by Django 4.0.4 on 2022-06-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_directory_options_alter_file_parent_directory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name': 'Directory', 'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='root_directory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.directory'),
        ),
    ]
