# Generated by Django 4.0.4 on 2022-06-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_directory_options_alter_profile_root_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
